restaurant_arry = [
    ["Quick Service", ["McDonald's", 1]],
    ["Quick Service", ["Chick-fil-A", 3]],
    ["Quick Service", ["KFC", 14]],
    ["Casual Dining", ["Olive Garden", 15]],
    ["Casual Dining", ["Applebee's", 16]],
    ["Quick Service", ["Taco Bell", 4]],
    ["Casual Dining", ["Red Lobster", 31]],
    ["Family Dining", ["Cracker Barrel", 32]],
    ["Casual Dining", ["The Cheesecake Factory", 33]],
    ["Fast Casual", ["Jimmy John's Gourmet Sandwiches", 34]],
    ["Quick Service", ["Hardee's", 35]],
    ["Fast Casual", ["Zaxby's", 36]],
    ["Quick Service", ["Pizza Hut", 11]],
    ["Fast Casual", ["Chipotle Mexican Grill", 12]],
    ["Quick Service", ["Sonic Drive-In", 13]],
    ["Quick Service", ["Burger King", 5]],
    ["Quick Service", ["Subway", 6]],
    ["Quick Service", ["Wendy's", 7]],
    ["Quick Service", ["Dunkin", 8]],
    ["Casual Dining", ["Buffalo Wild Wings", 22]],
    ["Casual Dining", ["Chili's Grill & Bar", 23]],
    ["Quick Service", ["Jack in the Box", 24]],
    ["Family Dining", ["IHOP", 25]],
    ["Casual Dining", ["Texas Roadhouse", 26]],
    ["Casual Dining", ["LongHorn Steakhouse", 37]],
    ["Fast Casual", ["Wingstop", 44]],
    ["Family Dining", ["Waffle House", 45]],
    ["Fast Casual", ["Jersey Mike's Subs", 46]],
    ["Quick Service", ["Bojangles", 47]],
    ["Quick Service", ["Culver's", 38]],
    ["Quick Service", ["Golden Corral", 39]],
    ["Fast Casual", ["Five Guys Burgers and Fries", 40]],
    ["Quick Service", ["Krispy Kreme", 55]],
    ["Casual Dining", ["Red Robin Gourmet Burgers and Brews", 41]],
    ["Fast Casual", ["Raising Cane's Chicken Fingers", 42]],
    ["Quick Service", ["Carl's Jr.", 43]],
    ["Fast Casual", ["McAlister's Deli", 63]],
    ["Casual Dining", ["Cheddar's Scratch Kitchen", 64]],
    ["Quick Service", ["Church's Chicken",65]],
    ["Quick Service", ["Tim Hortons", 66]],
    ["Steak", ["Ruth's Chris Steak House", 67]],
    ["Casual Dining", ["Carrabba's Italian Grill", 68]],
    ["Quick Service", ["Arby's", 18]],
    ["Quick Service", ["Domino's", 9]],
    ["Family Dining", ["Denny's", 27]],
    ["Quick Service", ["Papa John's", 28]],
    ["Casual Dining", ["P.F. Chang's", 52]],
    ["Fast Casual", ["Qdoba Mexican Eats", 53]],
    ["Quick Service", ["El Pollo Loco", 54]],
    ["Casual Dining", ["Hooters", 56]],
    ["Fast Casual", ["Panera Bread", 10]],
    ["Casual Dining", ["Outback Steakhouse", 29]],
    ["Quick Service", ["Whataburger", 30]],
    ["Quick Service", ["Del Taco", 57]],
    ["Fast Casual", ["Panda Express", 17]],
    ["Quick Service", ["Starbucks", 2]],
    ["Family Dining", ["Bob Evans", 59]],
    ["Fast Casual", ["Moe's Southwest Grill", 60]],
    ["Quick Service", ["Papa Murphy's Pizza", 61]],
    ["Casual Dining", ["Ruby Tuesday", 62]],
    ["Quick Service", ["Popeyes Louisiana Kitchen", 19]],
    ["Quick Service", ["Little Caesars", 20]],
    ["Quick Service", ["Dairy Queen", 21]],
    ["Casual Dining", ["BJ's Restaurant & Brewhouse", 48]],
    ["Casual Dining", ["TGI Fridays", 49]],
    ["Quick Service", ["In-N-Out Burger", 50]],
    ["Quick Service", ["Steak 'n Shake", 51]],
    ["Fast Casual", ["Firehouse Subs", 58]]

    
]